version: "3"

services:

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always # restart policy: Restart on error, crash or whatever
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80

  backend:
    image: complex/backend
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/ # Which folder to look for the Dockerfile
    volumes:
      - /app/node_modules/ # Ignore node_modules
      - ./backend/:/app/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # name of the service
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  frontend:
    image: complex/frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend/
    stdin_open: True
    volumes:
      - /app/node_modules/
      - ./frontend/:/app/

  worker:
    image: complex/worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker/
    volumes:
      - /app/node_modules
      - ./worker:/app/
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis
